name: Rust

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install SQLite (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Install SQLite (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        choco install sqlite
        cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib
    - name: Add environment variables (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_PATH
        echo "SQLITE3_LIB_DIR=C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_ENV
        echo "SQLITE_DATABASE_URL=C:\test.db" >> $GITHUB_ENV
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt install libsqlite3-dev
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: rustfmt
        run: cargo fmt -- --check
